Repository webdriverio-community/wdio-electron-service, pull requests merged in 2025-02, with the labels that each got.

#913 chore: update pnpm to address Dependabot failures
  package.json
Labels: dependencies, CI, backport-requested

#888 feat: support window management
  README.md
  apps/builder-cjs/package.json
  apps/builder-cjs/src/main.ts
  apps/builder-cjs/src/preload.ts
  apps/builder-cjs/src/splash.html
  apps/builder-esm/package.json
  apps/builder-esm/src/main.ts
  apps/builder-esm/src/preload.cts
  apps/builder-esm/src/splash.html
  apps/forge-cjs/package.json
  apps/forge-cjs/src/main.ts
  apps/forge-cjs/src/preload.ts
  apps/forge-cjs/src/splash.html
  apps/forge-esm/package.json
  apps/forge-esm/src/main.ts
  apps/forge-esm/src/preload.cts
  apps/forge-esm/src/splash.html
  apps/no-binary-cjs/package.json
  apps/no-binary-cjs/src/main.ts
  apps/no-binary-cjs/src/preload.ts
  apps/no-binary-cjs/src/splash.html
  apps/no-binary-esm/package.json
  apps/no-binary-esm/src/main.ts
  apps/no-binary-esm/src/preload.cts
  apps/no-binary-esm/src/splash.html
  docs/window-management.md
  e2e/package.json
  e2e/test/window/window.multiremote.spec.ts
  e2e/test/window/window.spec.ts
  e2e/wdio.conf.ts
  e2e/wdio.multiremote.conf.ts
  e2e/wdio.no-binary.conf.ts
  e2e/wdio.no-binary.multiremote.conf.ts
  package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-types/src/index.ts
  packages/@wdio_electron-utils/package.json
  packages/wdio-electron-service/package.json
  packages/wdio-electron-service/src/service.ts
  packages/wdio-electron-service/src/window.ts
  packages/wdio-electron-service/test/service.spec.ts
  packages/wdio-electron-service/test/window.spec.ts
  pnpm-lock.yaml
Labels: enhancement

#917 chore: update deps
  apps/builder-cjs/package.json
  apps/builder-esm/package.json
  apps/forge-cjs/package.json
  apps/forge-esm/package.json
  apps/no-binary-cjs/package.json
  apps/no-binary-esm/package.json
  e2e/package.json
  e2e/test/api.spec.ts
  package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-utils/package.json
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: dependencies

#923 chore: docs for Maintenance policy and automate backport operation
  docs/development.md
  package.json
  pnpm-lock.yaml
  scripts/backport.ts
Labels: documentation, tooling, backport-requested

#929 chore: add the dependabot configuration for maintenance version
  .github/dependabot.yml
  .github/workflows/release.yml
  docs/development.md
Labels: documentation, dependencies, backport-requested

#937 feat: support object inspection at debug log
  packages/@wdio_electron-utils/src/log.ts
Labels: tooling, backport-requested

#946 chore: update deps
  package.json
  packages/@wdio_electron-bundler/package.json
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: dependencies

#948 chore: add `--access=public` to publish
  scripts/publish.ts
Labels: CI

#958 ci: use `lts` and `lts-next` tags for NPM when releasing from a non-main branch
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: backport-requested

#967 fix: broken $ and $$ types
  e2e/test/dom.spec.ts
  e2e/test/interaction.spec.ts
  packages/@wdio_electron-types/src/index.ts
  pnpm-lock.yaml
Labels: bug, backport-requested
