Repository webdriverio-community/wdio-electron-service, pull requests merged in 2025-04, with the labels that each got.

#1064 refactor(utils): module partitioning of `getBinaryPath `
  packages/@wdio_electron-utils/src/appBuildInfo.ts
  packages/@wdio_electron-utils/src/binaryPath.ts
  packages/@wdio_electron-utils/src/config/builder.ts
  packages/@wdio_electron-utils/src/config/forge.ts
  packages/@wdio_electron-utils/src/constants.ts
  packages/@wdio_electron-utils/src/electronVersion.ts
  packages/@wdio_electron-utils/src/getBinaryPath.ts
  packages/@wdio_electron-utils/src/index.ts
  packages/@wdio_electron-utils/src/pnpm.ts
  packages/@wdio_electron-utils/src/selectExecutable.ts
  packages/@wdio_electron-utils/test/__mock__/log.ts
  packages/@wdio_electron-utils/test/appBuildInfo.spec.ts
  packages/@wdio_electron-utils/test/binaryPath.spec.ts
  packages/@wdio_electron-utils/test/config/builder.spec.ts
  packages/@wdio_electron-utils/test/config/forge.spec.ts
  packages/@wdio_electron-utils/test/electronVersion.spec.ts
  packages/@wdio_electron-utils/test/getBinaryPath.spec.ts
  packages/@wdio_electron-utils/test/index.spec.ts
  packages/@wdio_electron-utils/test/pnpm.spec.ts
  packages/@wdio_electron-utils/test/selectExecutable.spec.ts
  packages/@wdio_electron-utils/test/testUtils.ts
  packages/@wdio_electron-utils/test/tsconfig.json
Labels: area:tests, semver:patch, track:main

#961 feat(cdp): implementation of `cdp-bridge`
  packages/@wdio_electron-cdp-bridge/README.md
  packages/@wdio_electron-cdp-bridge/e2e/node.spec.ts
  packages/@wdio_electron-cdp-bridge/e2e/tsconfig.json
  packages/@wdio_electron-cdp-bridge/package.json
  packages/@wdio_electron-cdp-bridge/rollup.config.ts
  packages/@wdio_electron-cdp-bridge/src/bridge.ts
  packages/@wdio_electron-cdp-bridge/src/constants.ts
  packages/@wdio_electron-cdp-bridge/src/devTool.ts
  packages/@wdio_electron-cdp-bridge/src/index.ts
  packages/@wdio_electron-cdp-bridge/src/types.ts
  packages/@wdio_electron-cdp-bridge/test/bridge.spec.ts
  packages/@wdio_electron-cdp-bridge/test/devTool.spec.ts
  packages/@wdio_electron-cdp-bridge/test/tsconfig.json
  packages/@wdio_electron-cdp-bridge/tsconfig.json
  packages/@wdio_electron-cdp-bridge/vitest.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/publish.ts
  turbo.json
Labels: type:enhancement, release:future, semver:major, track:next

#1066 feat(cdp): add ability to assign the debugger port worker by worker
  packages/wdio-electron-service/package.json
  packages/wdio-electron-service/src/capabilities.ts
  packages/wdio-electron-service/src/launcher.ts
  packages/wdio-electron-service/test/capabilities.spec.ts
  packages/wdio-electron-service/test/launcher.spec.ts
  pnpm-lock.yaml
Labels: type:enhancement, release:future, semver:major, track:next

#1073 chore: enable tooling caches
  .github/workflows/_ci-lint.reusable.yml
  .gitignore
  e2e/package.json
  package.json
  turbo.json
Labels: area:ci, area:tooling, release:next, track:main

#1074 ci: add PR title check
  .github/workflows/pr-title.yml
Labels: area:ci, release:next, track:main

#1075 chore: remove root `.npmrc`
  .npmrc
Labels: component:electron-builder, area:tooling, release:next, track:main
