Repository webdriverio-community/wdio-electron-service, pull requests merged in 2025-03, with the labels that each got.

#983 chore(v7): update deps
  apps/builder-cjs/package.json
  apps/builder-esm/package.json
  apps/forge-cjs/package.json
  apps/forge-esm/package.json
  apps/no-binary-cjs/package.json
  apps/no-binary-esm/package.json
  e2e/package.json
  package.json
  packages/@wdio_electron-bundler/package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-utils/package.json
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: maintenance-version-dependencies

#966 test: add missing unit test
  packages/@wdio_electron-bundler/test/index.spec.ts
  packages/@wdio_electron-bundler/test/plugins.spec.ts
  packages/@wdio_electron-bundler/test/utils.spec.ts
  packages/@wdio_electron-utils/test/index.spec.ts
  packages/wdio-electron-service/test/capabilities.spec.ts
  packages/wdio-electron-service/test/commands/clearAllMocks.spec.ts
  packages/wdio-electron-service/test/commands/execute.spec.ts
  packages/wdio-electron-service/test/commands/isMockFunction.spec.ts
  packages/wdio-electron-service/test/commands/mock.spec.ts
  packages/wdio-electron-service/test/commands/mockAll.spec.ts
  packages/wdio-electron-service/test/commands/resetAllMocks.spec.ts
  packages/wdio-electron-service/test/commands/restoreAllMocks.spec.ts
  packages/wdio-electron-service/test/launcher.spec.ts
  packages/wdio-electron-service/test/main.spec.ts
  packages/wdio-electron-service/test/mock.spec.ts
  packages/wdio-electron-service/test/mockStore.spec.ts
  packages/wdio-electron-service/test/preload.spec.ts
  packages/wdio-electron-service/test/service.spec.ts
  packages/wdio-electron-service/test/session.spec.ts
  packages/wdio-electron-service/test/versions.spec.ts
  packages/wdio-electron-service/test/window.spec.ts
Labels: tests

#986 ci: improvements of the release processing
  .github/workflows/pre-release.yml
  .github/workflows/release-main.yml
  .github/workflows/release.yml
Labels: CI

#1001 chore: update deps
  apps/builder-cjs/package.json
  apps/builder-esm/package.json
  apps/forge-cjs/package.json
  apps/forge-esm/package.json
  apps/no-binary-cjs/package.json
  apps/no-binary-esm/package.json
  e2e/package.json
  package.json
  packages/@wdio_electron-bundler/package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-utils/package.json
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: dependencies, track:maintenance

#1004 ci: create maintenance branch automatically
  .github/workflows/release-shared.yml
Labels: area:ci

#960 ci: automate major release tasks
  .github/dependabot.yml
  .github/templates/archived-template.md
  .github/templates/maintenance-template.md
  .github/workflows/_release-calculate.reusable.yml
  .github/workflows/_release-orchestration.reusable.yml
  .github/workflows/_release-post.reusable.yml
  .github/workflows/_release-prepare.reusable.yml
  .github/workflows/_release-publish.reusable.yml
  .github/workflows/actions/build-verify/action.yml
  .github/workflows/actions/setup-workspace/action.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  docs/development.md
  docs/release-management.md
  scripts/backport.ts
  scripts/create-milestones.ts
  scripts/update-maintenance-docs.ts
  scripts/update-release-labels.ts
Labels: area:ci, release:next, semver:patch, track:main

#1014 chore: update deps
  apps/builder-cjs/package.json
  apps/builder-esm/package.json
  apps/forge-cjs/package.json
  apps/forge-esm/package.json
  apps/no-binary-cjs/package.json
  apps/no-binary-esm/package.json
  e2e/package.json
  packages/@wdio_electron-bundler/package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-utils/package.json
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: area:dependencies, track:main

#1015 chore: update configuration for dependabot
  .github/dependabot.yml
Labels: area:dependencies

#1018 chore(v7): update deps
  apps/builder-cjs/package.json
  apps/builder-esm/package.json
  apps/forge-cjs/package.json
  apps/forge-esm/package.json
  apps/no-binary-cjs/package.json
  apps/no-binary-esm/package.json
  e2e/package.json
  package.json
  packages/@wdio_electron-bundler/package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-utils/package.json
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: area:dependencies, track:maintenance

#1013 test: remove unnecessary await
  e2e/test/interaction.spec.ts
Labels: area:ci, area:tests

#1024 maintenance: add typesVersions to package.json
  packages/@wdio_electron-utils/package.json
Labels: release:next, track:maintenance

#1023 maintenance: update dependencies
  apps/builder-cjs/package.json
  apps/builder-esm/package.json
  apps/forge-cjs/package.json
  apps/forge-esm/package.json
  apps/no-binary-cjs/package.json
  apps/no-binary-esm/package.json
  e2e/package.json
  package.json
  packages/@wdio_electron-bundler/package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-utils/package.json
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: area:dependencies, release:next, track:maintenance

#1025 ci: standardise branch names around `v{MAJOR_VERSION}.x`
  .github/workflows/_release-calculate.reusable.yml
Labels: area:ci

#1027 ci: fix dry-run handling
  .github/workflows/_release-orchestration.reusable.yml
  .github/workflows/_release-post.reusable.yml
  .github/workflows/_release-prepare.reusable.yml
  .github/workflows/_release-publish.reusable.yml
  .github/workflows/actions/build-verify/action.yml
Labels: area:ci, release:next, track:main

#1032 chore: remove unnecessary dep
  packages/@wdio_electron-utils/package.json
  pnpm-lock.yaml
Labels: area:dependencies, backport:requested, track:main

#1035 ci: add major release feature branch and fix maintenance branch name
  .github/workflows/ci.yml
  .github/workflows/pre-release.yml
Labels: area:ci, release:next, track:main

#1043 chore: fix to invalid group configuration for the dependabot
  .github/dependabot.yml
Labels: area:dependencies, area:ci, area:tooling, backport:requested, track:main

#1042 test: add wait step to the interaction e2e test
  e2e/test/interaction.spec.ts
Labels: type:bug, area:tests, track:main

#1051 chore: remove forge yarn hack
  .github/assets/e2e-graph-mac-universal.png
  .github/assets/e2e-graph.png
  .gitignore
  apps/forge-cjs/yarn.lock
  apps/forge-esm/yarn.lock
  package.json
  scripts/clean-yarn-artifacts.ts
  scripts/create-yarn-package.ts
  scripts/init-forge-apps.ts
  turbo.json
Labels: area:ci, component:electron-forge, area:tooling, release:next, track:main

#1050 test: remove `@testing-library/webdriverio`
  e2e/package.json
  e2e/rollup.config.js
  e2e/test/dom.spec.ts
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
Labels: area:dependencies, area:tests, release:next, track:main

#978 ci: improve performance of CI job
  .github/workflows/README.md
  .github/workflows/_ci-build.reusable.yml
  .github/workflows/_ci-e2e.reusable.yml
  .github/workflows/_ci-lint.reusable.yml
  .github/workflows/_ci-unit.reusable.yml
  .github/workflows/actions/download-archive/action.yml
  .github/workflows/actions/setup-workspace/action.yml
  .github/workflows/actions/upload-archive/action.yml
  .github/workflows/ci.yml
  apps/forge-cjs/.npmrc
  apps/forge-esm/.npmrc
  e2e/package.json
  e2e/test/standalone/api.no-binary.spec.ts
  e2e/test/standalone/api.spec.ts
  e2e/wdio.conf.js
  e2e/wdio.conf.ts
  package.json
Labels: area:dependencies, area:ci, component:electron-builder, component:electron-forge, release:next, semver:patch, track:main

#1055 feat: support PNPM catalogs
  e2e/test/standalone/api.no-binary.spec.ts
  e2e/test/standalone/api.spec.ts
  e2e/wdio.no-binary.conf.js
  e2e/wdio.no-binary.conf.ts
  packages/@wdio_electron-utils/src/index.ts
  packages/@wdio_electron-utils/test/index.spec.ts
  packages/wdio-electron-service/src/launcher.ts
Labels: type:enhancement, release:next, semver:minor, track:main

#1056 chore: use PNPM catalogs
  apps/README.md
  apps/builder-cjs/package.json
  apps/builder-esm/package.json
  apps/forge-cjs/package.json
  apps/forge-esm/package.json
  apps/no-binary-cjs/package.json
  apps/no-binary-esm/package.json
  docs/development.md
  e2e/package.json
  fixtures/cjs/builder-dependency-inline-config/package.json
  fixtures/cjs/multiple-build-tools-config/package.json
  fixtures/esm/builder-dependency-inline-config/package.json
  fixtures/esm/forge-dependency-js-config/forge.config.js
  fixtures/esm/forge-dependency-linked-js-config/custom-config.js
  fixtures/esm/multiple-build-tools-config/package.json
  fixtures/pnpm/package.json
  fixtures/pnpm/packages/app1/package.json
  fixtures/pnpm/packages/app2/package.json
  fixtures/pnpm/packages/app2/pnpm-workspace.yaml
  fixtures/pnpm/pnpm-workspace.yaml
  package.json
  packages/@wdio_electron-bundler/package.json
  packages/@wdio_electron-types/package.json
  packages/@wdio_electron-utils/package.json
  packages/@wdio_electron-utils/src/config/builder.ts
  packages/@wdio_electron-utils/src/config/forge.ts
  packages/@wdio_electron-utils/src/config/read.ts
  packages/@wdio_electron-utils/src/constants.ts
  packages/@wdio_electron-utils/src/getAppBuildInfo.ts
  packages/@wdio_electron-utils/src/getBinaryPath.ts
  packages/@wdio_electron-utils/src/getElectronVersion.ts
  packages/@wdio_electron-utils/src/index.ts
  packages/@wdio_electron-utils/src/pnpm.ts
  packages/@wdio_electron-utils/test/config/builder.spec.ts
  packages/@wdio_electron-utils/test/config/forge.spec.ts
  packages/@wdio_electron-utils/test/getAppBuildInfo.spec.ts
  packages/@wdio_electron-utils/test/getBinaryPath.spec.ts
  packages/@wdio_electron-utils/test/getElectronVersion.spec.ts
  packages/@wdio_electron-utils/test/index.spec.ts
  packages/@wdio_electron-utils/test/pnpm.spec.ts
  packages/@wdio_electron-utils/test/testUtils.ts
  packages/@wdio_electron-utils/vitest.config.ts
  packages/wdio-electron-service/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/switch-catalog.ts
  scripts/update-catalogs.ts
Labels: type:enhancement, area:dependencies, release:future, semver:patch, track:main
